### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lorenzgerber** [lessthanoptimal/Auto64Fto32F#1]
Hi Peter,
I wonder whether there is a specific reason why this project is 'unlicensed' while 'EJML' that since Version 0.31 depends upon it is under 'Apache 2.0'. I currently contribute to an eclipse foundation open-source project that uses EJML 0.29. Recently, I wanted to upgrade, however the project owner rejected my request as he argued that the 'unlicense' is not compatible with license requirements within the eclipse foundation. I'm no legal expert, but I guess that changing 'Auto64Fto32F' to Apache 2.0 would do the trick. However, I'm aware that things are as they are and that you might have your reasons. Hence, this is only a kind request of a simple dev who would love to use and enjoy your wonderful library in the most recent version :)
Cheers from Sweden
Lorenz

**Comment by lessthanoptimal** [comment]
Hi Lorenz,

Before answering your question I would like to point out that this is probably a non-issue. Auto64Fto32F is a pre-compile dependency. It autogenerates code and is not a library that the EJML jar is dependent on. If you include EJML in your gradle/maven project Auto64Fto32F should not show up in the dependency tree. The SNAPSHOT depends on gversion plugin is has been released under the same license and is also not a runtime dependency.

Now back to your question. Ironically I released it to the public domain to make it trivial for anyone to use code from that project in their project. The idea was that if you wanted part or some of that code you could just cut and paste what you wanted and not have to worry about updating your license or keep track of who the original author was. Unfortunately it appears to have accomplished the opposite of that so far!

I'm curious why public domain/unlicensed isn't valid. I think there's a default clause in the unlicensed agreement for jurisdictions where the concept public domain doesn't exist.

- Peter

P.S. There's a script for upgrading older projects to 0.31 on EJML's website. I would try using it. Might need to tweak it some for the latest stable version 0.34.

**Comment by lorenzgerber** [comment]
Hi Peter,
Thanks for the quick reply. I'm no law expert. As I interpret the discussions cited on wikipedia, the problem is that the fall-back license relates to the concept of 'public-domain' which does not exist in many legal systems (eg EU law). Hence, there seems to be insecurity to how certain cases such as patent claims by code contributors would be judged which is a no-go when you develop open-source software for a living in a commercial setting.
As of whether this is a non-issue or not, I need to check back with the project lead. Afaik, the problem is that we include all sources also from the dependencies in our product (we develop Eclipse RCP software).
Thanks again for your time
Lorenz

**Comment by lessthanoptimal** [comment]
Would releasing it under CC0 fix the issue?

https://en.wikipedia.org/wiki/Creative_Commons_license#Zero_/_public_domain

**Comment by lorenzgerber** [comment]
imho, same issue: https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F
eg. if you are a private person, no problem, if you are a company developing and depending on FOSS, rather not (don't get me wrong, I think I understand your motivation for the 'Unlicense' or 'CC0': no time to bother about legal crap while doing a good thing for the community... I fully agree and I also don't know what is the best way here... was just curious because you chose Apache 2.0 for EJML. Did you got any issues with that?)

**Comment by lessthanoptimal** [comment]
The size of the project mainly. For those much smaller projects which have been customized for my needs I could see someone just wanting to cut and paste a few lines of code. This way they aren't violating a license agreement when they do so and don't add the license to their project. Granted violating an open source license rarely stops people from borrowing a few lines of code.

Is the main issue that if no one owns the code which is used and it violates a patent you are worried that the patent owner will sue your project? I think that's the case no matter what. For example it's my understanding that if someone added code to the Linux kernel which was covered by a patent I'm violating the patent even though I'm use a user and can technically be sued by them or forced to pay a licensing fee. Doesn't matter if the person who donated the code claimed that it was patent free or not when they did the donation.

**Comment by lorenzgerber** [comment]
I'll drop a mail at license@eclipse.org (https://www.eclipse.org/legal/licenses.php) to ask if CC0 is acceptable. Apparently, some also applied double licensing after a similar issue: https://github.com/docopt/docopt.rs/issues/1 , https://opensource.stackexchange.com/questions/5601/can-software-be-both-mit-licensed-and-in-the-public-domain/5602
I can ask that on top at eclipse.

**Comment by lorenzgerber** [comment]
Please find below the answer from Sharon Corbett of the Eclipse Foundation:
_"While we have third party content approved subject to public domain and CC0-1.0, strong preference would be given to using the content under the MIT License[1].
If the author has the ability to re-license, it would be great if the project could be dual licensed under the MIT as well."_

**Comment by lessthanoptimal** [comment]
See the latest SNAPSHOT for the new license

https://github.com/lessthanoptimal/Auto64Fto32F/tree/SNAPSHOT

changes are in README and in files added.

**Comment by lorenzgerber** [comment]
Thanks, and sorry again for hassling you about such stuff (errr, could you do the same thing also in the gversion-plugin...)
